test: &default

  # Credentials for REST APIs
  client_id: AT1g_pU0yWw2jGYuqh864eIP2lYZLKHI0EXFmuoXlZpW098cL1uP02MJAw5WFLJSqSfTXu1U2MRiQ4BP
  client_secret: ENlLXQv-Jubu67EgoKcSJxx0Romv8XEQSEXYPCOLuoHNDIyL34rd7W6gOcBAXAJ8w-O4WmE8JAPLQmLd

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
#  app_id: APP-80W284485P519543T
#  username: jb-us-seller_api1.paypal.com
#  password: WX4WTU3S8MY44S7F
#  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
#  sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  client_id: <%= ENV['PAYPAL_CLIENT_ID'] %>
  client_secret: <%= ENV['PAYPAL_CLIENT_SECRET'] %>
  mode: live
